### ISSUE TITLE
Queue stats not available

### ISSUE THREAD

**Issue by mikemand** [eyewitness/eye#9]
Hi again. I've been using Eyewitness for a little over a day now, and I've noticed that the queue stats are not being tracked. The monitor is also saying the queue is offline, even though it isn't. See below for screenshots.

![screen shot 2018-02-08 at 6 03 35 pm](https://user-images.githubusercontent.com/745184/36006528-b4f23550-0cfa-11e8-8368-60dce939f839.png)
![screen shot 2018-02-08 at 6 03 49 pm](https://user-images.githubusercontent.com/745184/36006532-b975277c-0cfa-11e8-8d6a-f1ccdd4b7caa.png)

Same environment as #7. I _have_ noticed that my queue seems to get stuck sometimes but after I restart it, it chews through the backlog just fine.

**Comment by laurencei** [comment]
Can you try changing the following in your `.ENV` file

`EYEWITNESS_DEBUG=true`

Then make sure you run `queue:restart` and also `config:cache` (if you have cached config).

Then after a short time - see if anything appears in your log files? The debug mode shows up extra things that might help point to the cause.

Also - can you please let me know the full queue command you are running? i.e. `queue:work --tries=3 ...`

**Comment by mikemand** [comment]
Hi @laurencei,

I enabled debug mode about 20 minutes ago and (after restarting my queue) ran `php artisan eyewitness:poll --force` to force an update. There is nothing from eyewitness in my logs.

My queue command is: `php /home/forge/website.com/artisan queue:work beanstalkd --sleep=15 --daemon --quiet --timeout=60 --env=production --queue=default`

**Comment by laurencei** [comment]
Thanks. Can I ask what PHP version and Laravel version you are running as
well?

And just confirming you also ran “config:cache” (if needed) and
“queue:restart” as well?

**Comment by mikemand** [comment]
```
➜ php -v
PHP 7.2.2-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Feb  1 2018 16:01:26) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.2-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
```

I cannot cache my config, as I have a couple of closures in one of the config files. But yes, I did restart the queue.

**Comment by laurencei** [comment]
Sorry, one last question; what cache driver are you using?

I’m going to try to replicate the situation today

**Comment by mikemand** [comment]
Hi @laurencei,

Not a problem. :) Cache is actually currently set to `array`.  That's one area that I haven't had time to figure out yet, lol.

**Comment by mikemand** [comment]
This may or may not be related, but the DNS and SSL monitors are not working either:

![screen shot 2018-02-09 at 5 31 07 pm](https://user-images.githubusercontent.com/745184/36056137-162b5b16-0dbf-11e8-8038-7b8d57745828.png)
![screen shot 2018-02-09 at 5 31 24 pm](https://user-images.githubusercontent.com/745184/36056141-179d0012-0dbf-11e8-89f5-5b2294c9ed7e.png)

The schedule is working great, however. :)
![screen shot 2018-02-09 at 5 35 34 pm](https://user-images.githubusercontent.com/745184/36056209-b12b1bf6-0dbf-11e8-9deb-abb3b9798549.png)

**Comment by laurencei** [comment]
Thanks @mikemand,

The `array` cache system is only designed for development. It literally is cleared at the end of each cycle.

If you've not choosen a cache, then for now `file` would probably be fine, although if you have `redis` on your server, I highly recommend that. `memcache` is also great.

If you could try changing to one of those, then restarting the queues, that should fix the problem I think (or at least rule out a few things).

**Comment by mikemand** [comment]
Hi @laurencei. I'm sorry it took me so long to get back to you.

I have set up `redis` for cache (Forge already has it installed and running; it seems like all I had to do was install the `predis/predis` package and change my `CACHE_DRIVER` env variable to `redis`). It has been running that way for a couple hours now, without any change to the queue stats, SSL, or DNS outputs.

**Comment by mikemand** [comment]
Hi @laurencei. New developments! It appears sometime yesterday that my queues started remembering the number of jobs they did.

![screen shot 2018-02-13 at 12 02 51 am](https://user-images.githubusercontent.com/745184/36137223-736dd422-1051-11e8-839a-01b1a14e5617.png)

SSL and DNS are still not working properly, and I now have a few duplicates in the Scheduler:

![screen shot 2018-02-13 at 12 05 20 am](https://user-images.githubusercontent.com/745184/36137256-9fea5b42-1051-11e8-9e80-57516e6275f4.png)

I'm not sure how _that_ happened, but progress is progress, yes?

**Comment by laurencei** [comment]
Hi @mikemand,

Did you re-install eyewitness and/or generate new token keys? The eyewitness commands are scheduled based upon your auto-generated tokens - so that would explain why they've been duplicated?

**Comment by mikemand** [comment]
I did not reinstall, but I may have run the `regenerate` command. I can't remember, sorry. :(

**Comment by laurencei** [comment]
No dramas. I am 99% sure the duplicated schedules are from the regenerate command.

In regards to the DNS + SSL - what does `dd(config('eyewitness.application_domains'))` show?

**Comment by laurencei** [comment]
@mikemand - due to a different issue, I might have another idea. We just updated the official docs to clarify that the `application_domains` setting must be a full url - not just the domain name.

So for example you need:

```diff
- 'application_domains' => ['www.yourdomain.com'],
+ 'application_domains' => ['https://www.yourdomain.com'],
```

For more see here: https://docs.eyewitness.io/configuration/general#domains

Can you let me know if that resolves the issue for you? Thanks

**Comment by mikemand** [comment]
That worked for DNS! I'm going to go ahead and let the scheduler do its thing for SSL. Should be checked within the next 20 minutes, so I will edit this comment when I know the results. :)

**Comment by mikemand** [comment]
As an aside, you could make the default `application_domains` be:

```php
    'application_domains' => [
        env('APP_URL'),
    ],
```

**Comment by laurencei** [comment]
thanks @mikemand - that's a good idea - I've made that change.
